# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Made in Cincy

# Short description (goes below the title; it will also be used in the RSS feed)
description: 'Made in Cincy: Cincinnati''s Creator Directory'

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.madeincincy.com

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md]

collections:
  companies:
    output: true
  events:
    output: true
  groups:
    output: true
  people:
    output: true
  projects:
    output: true