# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Made in Cincy

# Short description (goes below the title; it will also be used in the RSS feed)
description: 'Made in Cincy: Cincinnati''s Creator Directory'

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://www.madeincincy.com

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md]

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: /blog/:year/:month/:title/
paginate_path: /blog/page:num/

# Control the number of post per page
paginate: 10

# Additional GEMs to install
gems: [jekyll-paginate]

# Set the timezone so the update appears correctly
timezone: America/New_York

defaults:
  -
    scope:
      type: "company"
    values:
      baseName: "Companies"
      base: "/companies/"
  -
    scope:
      type: "event"
    values:
      baseName: "Events"
      base: "/events/"
  -
    scope:
      type: "group"
    values:
      baseName: "Groups"
      base: "/groups/"
  -
    scope:
      type: "person"
    values:
      baseName: "People"
      base: "/people/"
  -
    scope:
      type: "project"
    values:
      baseName: "Projects &amp; Products"
      base: "/projects/"

collections:
  companies:
    output: true
  events:
    output: true
  groups:
    output: true
  people:
    output: true
  projects:
    output: true